### ISSUE TITLE
Make rotating to South with a hatch compliant against the cargo intake

### ISSUE THREAD

**Issue by tcavarno** [errorcodexero/newarch#10]

**Comment by sjcbulldog** [comment]
Note, specifically, we expect the south side of the robot, the one with the cargo collector to be used for hatch collection.  So, I think we need to look at two things.  First, hatch collection on the south side of the robot needs to be rock solid.  Hatch placement also needs to work but will not be common based on our current strategy.  We likely will be able to do placement by just moving the hatch up three inches.  We have some play in the vertical direction.  However, I am more concerned about hatch collection on the south side.

**Comment by sjcbulldog** [comment]
Done
