### ISSUE TITLE
We need the climb sequence code

### ISSUE THREAD

**Issue by sjcbulldog** [errorcodexero/newarch#11]
We need the code to perform the climb sequence.  We first need to close with mechanical on what they expect the sequence to be and then get it implemented in code.

**Comment by 1425** [comment]
Climb sequence:
1) Align robot to base of level 3 hab.  We have been designing for 12" back, however we may be able to make this work with 0" back - but that hasn't been tested yet.  Also, make sure the ball ground pickup is retracted and the drive base is in low gear.
2) Release the latches and also trigger the ball ground pickup to extend.  
3) Wait 300 ms.  This is approximate and should be at least long enough for the wheels to leave the ground but not so long that the wheels are touching the platform.  
4) Turn on the drivebase's wheels in the direction to do further towards the platform.  I don't have a particular power number to use but relatively high would be good.
5) Wait till on the platform.  You may be able to tell this by seeing the accelerometers settle down or just by time.  
6) Turn off drive motors.

**Comment by sjcbulldog** [comment]
I assume this sequence is facing backward with the cargo intake facing toward the hab level 3 platform ?

**Comment by 1425** [comment]
Correct.

**Comment by sjcbulldog** [comment]
Done and verified
