### ISSUE TITLE
Need pit setup that allows access to roborio and raspberry pi in the pits via ethernet.

### ISSUE THREAD

**Issue by sjcbulldog** [errorcodexero/newarch#60]

**Comment by kd7mrx** [comment]
Butch,


When in the pit at competition, connect second radio port to an Ethernet switch with the pi and the driver station.  The radio will supply addresses via DHCP or you can set up static IP, netmask 255.0.0.0, no gateway, no DNS server.




At home, use the same setup or connect via wireless from driver station to radio.

**Comment by sjcbulldog** [comment]
switch ordered, will have in pits
