### ISSUE TITLE
Add field relative Turntable control

### ISSUE THREAD

**Issue by tcavarno** [errorcodexero/newarch#61]

**Comment by sjcbulldog** [comment]
Turns out the code is modular enough for OI processing that this was adding 20 lines of code that looked at the NavX and used its value (in quadrants) to look up the actual direction from a 4 by 4 array.

**Comment by 1425** [comment]
I see that this is listed as needing to be tested.  I'm not sure exactly what you have in mind, but this may need to be more than a power it on and see that it starts out doing the right thing.  

Historically many teams have had issues where over the course of a complete match the drift could get to be pretty big.  Like teams with field-relative swerves would have procedures where they would line up against a wall half way through and rezero.

**Comment by sjcbulldog** [comment]
We need to test this over a set of simulated matches.  However, the spec'ed drift on the NavX over time is one degree per minute.  The teams with field relative swerves were probably trying to do position as well as angle which is much less accurate.  We are only concerned about the angle for what is requested here.   Again the proof will be over simulated matches.

**Comment by sjcbulldog** [comment]
We will continue to watch this but over the course of the runs we did last night it seems to work well.

**Comment by 1425** [comment]
Excellent.  This should be fun to see in action.
