### ISSUE TITLE
Sandstorm path that allows us to collect cargo from the depot

### ISSUE THREAD

**Issue by tcavarno** [errorcodexero/newarch#63]

**Comment by sjcbulldog** [comment]
Does this mean after placing the center hatch we want to come back and collect cargo?  Please provide a step by step description of what is really wanted here.

**Comment by tcavarno** [comment]
Place a hatch on the cargo ship. deploy the cargo intake. drive path to cargo depot

**Comment by sjcbulldog** [comment]
This does not seem it is worth the effort.  Closing as won't fix.
