### ISSUE TITLE
Change the height we go to after cargo floor collect to be at cargo ship height

### ISSUE THREAD

**Issue by tcavarno** [errorcodexero/newarch#65]
the majority of the places where cargo is scored on the field is above level 1

**Comment by sjcbulldog** [comment]
Actually there are four heights, Rocket Level 1, Rocket Level 2, Rocket Level 3, and Cargo Ship.  I am assuming you want Cargo Ship height???

**Comment by sjcbulldog** [comment]
Ah i see the cargo ship height in the title, missed this when I first read it.

**Comment by sjcbulldog** [comment]
This is just a param in the params file.  Updated it from the level 1 height to the cargo ship height.
