### ISSUE TITLE
Cargo manipulation dependent on hatch sensor

### ISSUE THREAD

**Issue by 1425** [errorcodexero/newarch#72]
It seems that being able to collect cargo is dependent on the hatch sensor working correctly.  This is unintuitive and makes potential minor breakage unnecessarily severe.  

Specifically, the sequence we saw during the checkout of the practice bot was:
1) Collect a hatch
2) Go up to level 3
3) Hit button to try to collect a cargo
4) Robot ignores command to collect a cargo
5) Grab hatch off of robot
6) Robot now responds to command to collect a cargo

There might be some way to override this but nobody who was available knew how.  

The could be argued to be a safety feature so that you'd avoid accidentally collecting two game pieces, looked like it also meant that if the switch broke in such a way that it thought it had a hatch then you might have to give up on both hatches and cargo for the rest of the match.

**Comment by sjcbulldog** [comment]
This is not a safety features as much as a simplification for the OI.  Already there is way to much to keep up with the OI.  If in the manual mode, we use a single "Execute" button to execute the next action.  The next action is defined by any game piece in the robot as well as a single cargo/hatch switch when the robot is holding no piece.  Not only are we out of buttons on the OI already, but it is one less then for Tristan to keep up with.  To do something he hits a single button.

So, I would like to leave this as it is unless we cannot figure out a reliable hatch detect sensing mechanism.  Even with the somewhat reliable switch we have now I think we are in better shape than having tristan have to manage yet another switch.
