### ISSUE TITLE
Cargo pickup sequence has odd state

### ISSUE THREAD

**Issue by 1425** [errorcodexero/newarch#73]
The cargo pickup sequence seems to have an extra state that it's possible to get into where it is neither trying to pick up a ball anymore nor finished picking up the ball.  In particular what we saw running the practice bot tonight was:
1) Put the robot in cargo pickup mode.  Robot extends pickup, turns on collector wheels and holder wheels.
2) Briefly touch the switch in the holder and release it.  
3) The wheels on both the intake and the holder turn off and the intake does not retract.
This seems like a state the robot should never be in.

**Comment by sjcbulldog** [comment]
Found a state where if the IR sensor sending the ball coming in is not fired but the cargo presence switch in the cargo holder does fire, the floor collect cargo operation does the wrong thing.  Fixed but need to test today.
