### ISSUE TITLE
Reduce the pressure to the hatch holder arm when extended

### ISSUE THREAD

**Issue by sjcbulldog** [errorcodexero/newarch#79]
We are in a strange position.  We need to maintain outward pressure on the hatch holder arm when it is armed for place or collect so that random motion does not trigger the hall effect switch.  However, with outward pressure on the arm, at level 2 or level 3, the lift/turntable give enough that the hall effect switch is not triggered.  Hoping that reducing the pressure on the hatch arm will ease this some.  Note it is only an occasional issue.

**Comment by 1425** [comment]
Adding a second regulator to step down pressure is certainly possible.  Now that we've made the connection between the turntable and the base stiffer it would be interesting to know if this still occurs though.

**Comment by sjcbulldog** [comment]
Is this stiffness in the comp bot?  Is there something we need to do in the pits?

**Comment by 1425** [comment]
This is something we have planned for the comp bot and will want to do in the pits.
