### ISSUE TITLE
Create better motor management code for the CAN based motor controllers

### ISSUE THREAD

**Issue by sjcbulldog** [errorcodexero/newarch#84]
In general, robot subsystem will use CAN based motor controllers going forward.  There are three specific flavors of these motor controllers, the Victor SPX, the Talon SRX, and the Spark Max.  The Victor SPX and the TalonSRX are derived from a common base class but the Spark Max is not.  There needs to be some thinking about a motor factory and possibly a motor wrapper class so that subsystems can use these three motor types interchangeably with very little code modification.

**Comment by NobodyNada** [comment]
Implemented in #88
